In [1]:
import numpy as np
# https://numpy.org/doc/1.18/reference/generated/numpy.asarray.html

In [3]:
np.__version__

'1.18.1'

In [4]:
a = [1,2,3,4,5]
b = a*10
print(type(a),type(b))
a

<class 'list'> <class 'list'>


[1, 2, 3, 4, 5]

In [5]:
z = np.asarray([1,2,3,4,5])
type(z)

numpy.ndarray

In [6]:
z * 10 

array([10, 20, 30, 40, 50])

In [7]:
[1,2,3,"hola",True]

[1, 2, 3, 'hola', True]

In [8]:
z.dtype

dtype('int64')

In [9]:
z + z 

array([ 2,  4,  6,  8, 10])

In [10]:
q = np.concatenate([z,[33],z])
q

array([ 1,  2,  3,  4,  5, 33,  1,  2,  3,  4,  5])

In [12]:
a = np.asarray([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[1][1]

5

In [16]:
a[1,1]

5

In [17]:
a[1,:]

array([4, 5, 6])

In [19]:
a[1,0:2]

array([4, 5])

In [23]:
print(a.dtype)
print(a.size)
print(a.shape)
print("dim",len(a.shape))

int64
9
(3, 3)
dim 2


In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
q = np.eye(5) * 100
q

array([[100.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0., 100.]])

In [29]:
q.dtype

dtype('float64')

In [32]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.ones((5,5)) * 100 * (np.eye(5)-1) * -1

array([[ -0., 100., 100., 100., 100.],
       [100.,  -0., 100., 100., 100.],
       [100., 100.,  -0., 100., 100.],
       [100., 100., 100.,  -0., 100.],
       [100., 100., 100., 100.,  -0.]])

In [39]:
np.eye(5)-1

array([[ 0., -1., -1., -1., -1.],
       [-1.,  0., -1., -1., -1.],
       [-1., -1.,  0., -1., -1.],
       [-1., -1., -1.,  0., -1.],
       [-1., -1., -1., -1.,  0.]])

In [45]:
q = np.random.random((5,5))
print(q.size)
print(q.shape)
q

25
(5, 5)


array([[0.63988765, 0.20702588, 0.0080457 , 0.81518369, 0.63866557],
       [0.84734481, 0.5900436 , 0.0871867 , 0.50910074, 0.60052432],
       [0.28635149, 0.79522816, 0.9376986 , 0.5364843 , 0.8218072 ],
       [0.81679376, 0.62581767, 0.76839862, 0.6300748 , 0.78518111],
       [0.87620889, 0.38182381, 0.8427078 , 0.75228608, 0.23642326]])

In [48]:
q = np.random.random((5,5)) * np.eye(5)
q

array([[0.78972312, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.47852378, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.42985142, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.18463221, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.20557243]])

In [52]:
 for e in q:
    print("fila",e)
    for k in e:
        print("elemento",k)

fila [0.78972312 0.         0.         0.         0.        ]
elemento 0.7897231167358896
elemento 0.0
elemento 0.0
elemento 0.0
elemento 0.0
fila [0.         0.47852378 0.         0.         0.        ]
elemento 0.0
elemento 0.4785237835749596
elemento 0.0
elemento 0.0
elemento 0.0
fila [0.         0.         0.42985142 0.         0.        ]
elemento 0.0
elemento 0.0
elemento 0.4298514184729064
elemento 0.0
elemento 0.0
fila [0.         0.         0.         0.18463221 0.        ]
elemento 0.0
elemento 0.0
elemento 0.0
elemento 0.1846322084687585
elemento 0.0
fila [0.         0.         0.         0.         0.20557243]
elemento 0.0
elemento 0.0
elemento 0.0
elemento 0.0
elemento 0.2055724266069061


In [58]:
print(q)
z = q.tolist()
print(z)

[[0.78972312 0.         0.         0.         0.        ]
 [0.         0.47852378 0.         0.         0.        ]
 [0.         0.         0.42985142 0.         0.        ]
 [0.         0.         0.         0.18463221 0.        ]
 [0.         0.         0.         0.         0.20557243]]
[[0.7897231167358896, 0.0, 0.0, 0.0, 0.0], [0.0, 0.4785237835749596, 0.0, 0.0, 0.0], [0.0, 0.0, 0.4298514184729064, 0.0, 0.0], [0.0, 0.0, 0.0, 0.1846322084687585, 0.0], [0.0, 0.0, 0.0, 0.0, 0.2055724266069061]]


In [63]:
a = np.asarray([1,2,3])
b = [1,2,3]
print(a,b)
print(type(a),type(b))

[1 2 3] [1, 2, 3]
<class 'numpy.ndarray'> <class 'list'>


In [67]:
a = np.asarray([1,2,3,4])
a.sum()

10

In [68]:
a = np.random.random((5,4))
a

array([[0.31677612, 0.77457138, 0.43179638, 0.64855193],
       [0.30089365, 0.35881234, 0.04139569, 0.47515164],
       [0.33224287, 0.45234964, 0.57287155, 0.09397092],
       [0.64425788, 0.28430021, 0.13307726, 0.47906486],
       [0.79367847, 0.33049126, 0.09856565, 0.50013355]])

In [69]:
a.sum()

8.062953261576899

In [70]:
a.sum(axis=0)

array([2.387849  , 2.20052483, 1.27770653, 2.1968729 ])

In [71]:
a.sum(axis=1)

array([2.17169582, 1.17625332, 1.45143498, 1.5407002 , 1.72286894])

In [89]:
a = np.random.random((3,3,3))
a

array([[[0.57628129, 0.15040051, 0.01076523],
        [0.15696068, 0.75414679, 0.20056446],
        [0.64610882, 0.97401927, 0.78848049]],

       [[0.05082337, 0.12887348, 0.89104358],
        [0.31339229, 0.54759561, 0.50794359],
        [0.70263694, 0.78105633, 0.67071908]],

       [[0.04695436, 0.30585672, 0.70149667],
        [0.26893416, 0.24173403, 0.35052385],
        [0.6614718 , 0.84347551, 0.03988816]]])

In [96]:
a[:,:,2].T

array([[0.01076523, 0.89104358, 0.70149667],
       [0.20056446, 0.50794359, 0.35052385],
       [0.78848049, 0.67071908, 0.03988816]])

In [93]:
a[:,1].sum(axis=0)

array([0.73928713, 1.54347643, 1.0590319 ])

In [77]:
a.sum(axis=0)

array([[1.09128507, 0.77564341, 2.24993866],
       [0.97243003, 1.12407547, 1.62079309],
       [1.0367366 , 1.56104906, 1.20638077]])

In [ ]:
a

In [79]:
a = np.random.random((3,3))

In [85]:
b = np.concatenate([a,a], axis=0)
b

array([[0.86518384, 0.24068586, 0.37354675],
       [0.58859688, 0.53598563, 0.78992902],
       [0.76379676, 0.98016355, 0.75097065],
       [0.86518384, 0.24068586, 0.37354675],
       [0.58859688, 0.53598563, 0.78992902],
       [0.76379676, 0.98016355, 0.75097065]])

In [84]:
b.shape

(3, 6)

In [100]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [106]:
np.random.random((5,4,2,1,3)).T.shape

(3, 1, 2, 4, 5)

In [107]:
range(10)

range(0, 10)

In [109]:
np.arange(10, dtype="float")

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [114]:
a = np.arange(1,10)
print(a.shape)
a

(9,)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
np.eye(6).reshape((12,3))

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [134]:
a = np.random.random((5,4))
a

array([[0.73112392, 0.72228192, 0.55101966, 0.31198936],
       [0.45233489, 0.35339371, 0.69495122, 0.77545619],
       [0.88573553, 0.67175871, 0.49051556, 0.3532991 ],
       [0.22845701, 0.02902011, 0.35583802, 0.11994462],
       [0.65878966, 0.63572387, 0.36194077, 0.37323659]])

In [136]:
a.mean(axis=0)

array([0.5912882 , 0.48243566, 0.49085305, 0.38678517])

In [137]:
a.max(axis=0)

array([0.88573553, 0.72228192, 0.69495122, 0.77545619])

In [138]:
a.min(axis=0)

array([0.22845701, 0.02902011, 0.35583802, 0.11994462])

In [139]:
a.std(axis=0)

array([0.22880743, 0.26042435, 0.12658881, 0.21408799])

In [145]:
a = np.arange(9).reshape((3,3))
b = np.arange(9).reshape((3,3))
print(a)
print(b)
a*b

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [151]:
np.dot(a,b)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [153]:
a.dot(b)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [154]:
# https://en.wikipedia.org/wiki/Dot_product
a.dot([1,2,3])

array([ 8, 26, 44])

In [155]:
a * [1,2,3]

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [156]:
a = np.arange(10)
a / 0

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [158]:
0/0

ZeroDivisionError: division by zero