# Scipy - Linalg

```
 x + 3y + 5z = 10
2x + 5y +  z = 8
2x + 3y + 8z = 3
```

In [2]:
import numpy as np
from scipy import linalg

In [4]:
A = np.asarray([
    [1,3,5],
    [2,5,1],
    [2,3,8]
])

b = np.asarray([
    [10],
    [8],
    [3]
])


print(A)
print(b)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]


In [7]:
sol = linalg.solve(A,b)
sol

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [14]:
[x],[y],[z] = sol # Unpack
print(f"La solucion es -> X:{round(x,2)} Y:{round(y,2)} Z:{round(z,2)}")

La solucion es -> X:-9.28 Y:5.16 Z:0.76


In [16]:
def suma():
    return [5,8]

a,b = suma()
print(a,b)

5 8


# Scipy - stats

In [18]:
from scipy.stats import tmean

In [22]:
a = np.linspace(-10,10, 100)
print(a)
np.histogram(a)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

(array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
 array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.]))

In [23]:
tmean(a, limits=(-10,10))

-7.105427357601002e-17

In [24]:
tmean(a, limits=(0,10))

5.05050505050505

In [29]:
notas = [0,10,5,8,9,6,7,3,6,100]
print(np.mean(notas))
print(tmean(notas, limits=(0,10)))

15.4
6.0


# Pandas crosstab

In [34]:
data = np.asarray([
    ["foo", "foo", "foo", "foo", "bar", "bar", "bar","bar", "foo", "foo", "foo"],
    ["one", "one", "one", "two", "one", "one","one", "two", "two", "two", "one"],
    ["dull", "dull", "shiny", "dull", "dull", "shiny","shiny", "dull", "shiny", "shiny", "shiny"]
])
data

array([['foo', 'foo', 'foo', 'foo', 'bar', 'bar', 'bar', 'bar', 'foo',
        'foo', 'foo'],
       ['one', 'one', 'one', 'two', 'one', 'one', 'one', 'two', 'two',
        'two', 'one'],
       ['dull', 'dull', 'shiny', 'dull', 'dull', 'shiny', 'shiny',
        'dull', 'shiny', 'shiny', 'shiny']], dtype='<U5')

In [36]:
import pandas as pd

df = pd.DataFrame({"A":data[0], "B":data[1], "C":data[2]})
df

A    B      C
0   foo  one   dull
1   foo  one   dull
2   foo  one  shiny
3   foo  two   dull
4   bar  one   dull
5   bar  one  shiny
6   bar  one  shiny
7   bar  two   dull
8   foo  two  shiny
9   foo  two  shiny
10  foo  one  shiny

In [39]:
cr = pd.crosstab(df.A,[df.B, df.C])
cr

B    one        two      
C   dull shiny dull shiny
A                        
bar    1     2    1     0
foo    2     2    1     2

In [48]:
print(cr.columns)
cols = cr.columns[cr.columns.isin(["shiny"],level=1)]

a = cr[cols]
a

MultiIndex([('one',  'dull'),
            ('one', 'shiny'),
            ('two',  'dull'),
            ('two', 'shiny')],
           names=['B', 'C'])


B     one   two
C   shiny shiny
A              
bar     2     0
foo     2     2

In [53]:
a.iloc[0]

B    C    
one  shiny    2
two  shiny    0
Name: bar, dtype: int64

In [62]:
for index,rowSerie in a.iteritems():
    print(rowSerie.bar)

2
0


## Refs
- http://scipy.github.io/devdocs/tutorial/linalg.html
- http://scipy.github.io/devdocs/tutorial/stats.html
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html